name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            build-essential \
            git \
            zip \
            unzip \
            cython3
      
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36
      
      - name: Build APK with Buildozer
        run: |
          cd android_app
          export PIP_BREAK_SYSTEM_PACKAGES=1
          buildozer -v android debug
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: psychotalent-apk
          path: android_app/bin/*.apk
          if-no-files-found: error
      
      - name: Create Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: android_app/bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
